exports.ids = [1];
exports.modules = {

/***/ 67:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony default export */ __webpack_exports__["default"] = ({
  //common
  text_more: 'Daha Fazla',
  text_security_modal: 'Hesabınızın güvenlik seviyesi düşük. Lütfen aşağıdaki doğrulama yöntemlerinden en az 1 tanesini aktif ederek hesap güvenliğinizi arttırın.',
  text_email: 'E-posta',
  text_password: 'Parola',
  text_password_again: 'Parola (tekrar)',
  text_mobile: 'Telefon',
  text_withdraw: 'Çekme',
  text_deposit: 'Yatırma',
  text_phone_verification: 'Telefon Doğrulama',
  text_twofa_verification: 'Google Authenticator Doğrulama',
  text_remind: 'Daha sonra hatırlat',
  text_security_verification: 'Güvenlik Doğrulaması',
  text_twofa_label: '6 basamaklı Google 2FA doğrulama kodunu girin.',
  text_sms_label: 'Telefonunuza gelen 6 haneli doğrulama kodun girin.',
  text_twofa_code_label: 'Google 2FA Onay Kodu',
  text_sms_code_label: 'SMS Onay Kodu',
  text_twofa_placeholder: 'Google 2FA Kodunu Girin',
  text_sms_placeholder: 'SMS Kodunu Girin',
  text_new_password: 'Yeni Parola',
  text_new_password_again: 'Yeni Parola (tekrar)',
  text_send_code: 'Kodu Gönder',
  text_p2p_warning: 'P2P işlemlerine başlayabilmek için kimlik doğrulama işlemini tamamlamanız gerekmektedir.',
  text_available_balance: 'Kullanılabilir Bakiye',
  text_transfer: 'Transfer Et',
  text_show_low_balances: 'Düşük Bakiyeleri Göster',
  text_hide_low_balances: 'Düşük Bakiyeleri Gizle',
  text_copied: 'Kopyalandı',
  text_send: 'Gönder',
  text_current_password: 'Geçerli Parola',
  text_select: 'Seçiniz',
  text_date: 'Tarih',
  text_symbol: 'Çift',
  text_status: 'Durum',
  //Status
  NA: 'NA',
  FILLED: 'Tamamlandı',
  PARTIALLY_FILLED: 'Kısmen Tamamlandı',
  CANCELED: 'İptal',
  NEW: 'Yeni',
  //Order Type
  LIMIT: 'LİMİT',
  MARKET: 'PİYASA',
  // header texts
  text_home: 'Ana Sayfa',
  exchange_text: 'Al | Sat',
  swap_text: 'Hızlı Takas ',
  market_text: 'Tüm Piyasalar',
  text_wallet: 'Cüzdan',
  text_p2p: 'P2P',
  // header (user dropdown)
  text_identity: 'Kimlik',
  text_reward_center: 'Referans',
  text_logout: 'Çıkış Yap',
  // header notifications
  text_new_notifications: 'Yeni Bildirimler',
  text_see_all_notifications: 'Tümünü Gör',
  text_notification: 'Bildirim',
  text_all_notifications: 'Tüm Mesajlar',
  text_mark_all_as_read: 'Tümünü Oku',
  text_hide_read_notifications: 'Okunan Bildirimleri Gizle',
  text_delete_all: 'Tümünü Sil',
  text_delete_message: 'Mesaji Sil',
  login_text: 'Giriş Yap',
  signup_text: 'Üye Ol',
  // orders
  text_spot_orders: 'Spot Emirler',
  text_orders: 'Emirler',
  text_open_orders: 'Açık Emirler',
  text_p2p_order: 'P2P Emir',
  text_spot_order: 'Spot Emir',
  text_orderhistory: 'Emir Geçmişi',
  text_buyingsellinghistory: 'Al - Sat Geçmişi',
  text_buy: 'Satın Al',
  text_sell: 'Hızlı Takas',
  text_cancel: 'İptal',
  text_one_day: '1 Gün',
  text_one_week: '1 Hafta',
  text_one_month: '1 Ay',
  //account
  text_dashboard: 'Hesabım',
  text_payment: 'Banka',
  text_security: 'Güvenlik',
  text_settings: 'Ayarlar',
  text_basic_info: 'Temel Bilgiler',
  text_preferences: 'Tercihler',
  text_referral: 'Referans',
  text_wallets: 'Cüzdanlar',
  text_deposit: 'Yatırma',
  text_donotpull: 'Çekme',
  text_account_balance: 'Bakiye:',
  text_estimated_value: 'Yaklaşık Değer:',
  text_show_balance: 'Bakiye Göster',
  text_hide_balance: 'Bakiyeyi Gizle',
  text_purchase: 'Alım',
  text_sale: 'Satım',
  text_increase_security: 'Hesabınızın Güvenliğini Arttırın!',
  text_enable_2fa: '2FA Etkinleştir',
  text_authentication: 'Kimlik Doğrulama',
  text_two_step_verification: 'İki Adımlı | 2FA Doğrulama',
  text_google_authenticator: 'Google Authenticator',
  text_disable: 'Devre dışı bırak',
  text_activate: 'Aktifleştir',
  text_verified: 'Doğrulandı',
  text_not_verified: 'Doğrula',
  text_change: 'Değiştir',
  text_main_wallet: 'Ana Cüzdan',
  text_p2p_wallet: 'P2P Cüzdan',
  text_fiat_wallet: 'TL Cüzdan',
  text_announcements: 'Bildirimler',
  text_login_activity: 'Hareketler',
  text_browsers: 'Cihazlar',
  text_deactivate_account: 'Hesabı Devre Dışı Bırak',
  text_enterprise_account_reference: 'Kurumsal Hesap Başvurusu',
  // kyc
  text_continue: 'Devam',
  text_name: 'Ad',
  text_surname: 'Soyad',
  text_gender: 'Cinsiyet',
  text_birthday: 'Doğum Tarihi',
  text_address: 'Adres',
  text_postalcode: 'Posta Kodu',
  text_select_country: 'Ülke Seciniz',
  text_select_city: 'Şehir Seçiniz',
  text_select_nationality: 'Uyruk Seçiniz',
  text_vrf_foriegn_national: 'Türkiye Cumhuriyeti vatandaşları için TCKN, Türkiye’de ikamet eden yabancı uyruklu vatandaşları için YKN zorunludur.',
  //step 2
  text_document_standard: 'Belge',
  text_document_accuracy_text: 'Kimlik belgenizin ön ve arka yüzünü gönderiniz',
  text_file_types: 'Dosya Türleri: JPG, GIF, PNG veya PDF - 2MB olmalıdır.',
  text_high_res: 'Belge yüksek çözünürlüklü ve okunabilir olmalıdır',
  text_country: 'Ülke Seçiniz',
  text_front_doc: 'Belgenin Ön Yüzü',
  text_back_doc: 'Belgenin Arka Yüzü',
  text_select_photo: 'Fotoğraf Seçin',
  text_take_photo: 'Fotoğraf Çekin',
  text_document_type: 'Belge Tipi',
  text_document_is_required: 'Belge zorunludur',
  //step 3
  text_face_verification: 'Belge Doğrulama',
  text_face_standards: "Kimlik belgenizi teyit edebilmek için 'COINTRAL' ve Tarih içeren bir fotoğrafınızı yükleyiniz. Örn: ( COINTRAL 29.05.2020 )",
  // step 4
  text_kyc_complete: 'Tebrikler İşlem Tamamlandı!',
  text_kyc_complete_status: 'Kimlik doğrulama talebiniz bize ulaştı. En kısa sürede işleme alınacaktır.',
  text_return_to_homepage: 'Anasayfaya Dön',
  //enable 2fa
  text_step: 'Adım',
  text_enable_google_authenticator: 'Google Authenticator’ı Etkinleştirin',
  text_download_app: 'Uygulamayı İndir',
  text_scan_qr: 'QR Kodu Tara',
  text_save_key_title: 'Kurtarma Anahtarı',
  text_google_auth_enabled: 'Google Authenticator Etkinleştirildi',
  text_download_install: 'Google Authenticator uygulamasını indirin.',
  text_next: 'İleri',
  text_previous: 'Önceki',
  text_cant_scan: 'QR kodunu tarayamıyorsanız, kodu uygulamaya manuel olarak girebilirsiniz.',
  text_save_key: 'Lütfen bu anahtarı saklayın. Bu anahtar, 2FA cihazınıza erişememeniz durumunda Google Authenticator geri yüklemeniz içindir.',
  text_reset_google_auth: 'Google Authenticator (2FA) sıfırlamak için destek talebi açmanız gerekmektedir ve bu işlem en az 7 gün sürer.',
  //disable two fa
  text_disable_2fa_warning: 'Google Authenticator (2FA) | İki faktörlü doğrulamayı devre dışı bırakmak, risklidir. Devre dışı bırakırsanız, mümkün olan en kısa sürede yeniden etkinleştirmeniz önemle tavsiye edilir. 2FA devre dışı bırakıldıktan sonra 24 saat boyunca çekim işlemi gerçekleştiremezsiniz.',
  //enable sms
  text_enable_sms_auth: 'SMS Doğrulama',
  text_disable_sms_warning: 'SMS Doğrulama | İki faktörlü doğrulamayı devre dışı bırakmak, risklidir. Devre dışı bırakırsanız, mümkün olan en kısa sürede yeniden etkinleştirmeniz önemle tavsiye edilir. 2FA devre dışı bırakıldıktan sonra 24 saat boyunca çekim işlemi gerçekleştiremezsiniz.',
  text_enable_email_auth: 'E-posta Doğrulamayı Etkinleştir',
  // identity verification
  text_identity_verification: 'Kimlik Doğrulama',
  text_personal_information: 'Kişisel Bilgiler',
  text_id_information: 'Kimlik Bilgileri',
  text_face_verification: 'Kimlik Doğrulama',
  text_completed: 'Tamamlandı',
  text_contact_info: 'İletişim Bilgileri',
  // text_account_activities
  text_account_activities: 'Hesap Hareketleri',
  text_past_account_activity_record: 'Geçmiş Hesap Hareketleri',
  text_login_activities: 'Giriş Hareketleri',
  text_security_activity: 'Güvenlik Hareketleri',
  text_hour: 'Saat',
  text_status: 'Durum',
  // columns
  text_date: 'Tarih',
  text_type: 'Kaynak',
  text_ip_address: 'IP Adresi',
  text_no_records: 'Kayıt bulunamadı.',
  // preferences
  //common
  text_email: 'E-Posta',
  text_sms: 'SMS',
  //specific
  text_preferences: 'Bildirim',
  text_transaction_notifications: 'Bildirim Tercihleri',
  text_deposit_notices: 'Yatırma Bildirimleri',
  text_withdraw_notifications: 'Çekme Bildirimleri',
  text_p2p_notifications: 'P2P Bildirimleri',
  text_otc_statements: 'OTC Bildirimleri',
  text_security_settings_notifications: 'Güvenlik Bildirimleri',
  text_notification_lang_settings: 'Dil Seçenekleri',
  text_set_notification_lang: 'Bildirim Dilini Belirleyiniz',
  //security settings
  // common
  text_confirmed: 'Doğrulandı',
  text_used_for: 'Çekim işlemleri - Güvenlik Değişiklikleri',
  // specific
  text_email_authentication: 'E-posta Doğrulama',
  text_sms_authentication: 'SMS Doğrulama',
  text_google_authentication: 'Google 2FA Doğrulama',
  text_device_management: 'Cihaz Yönetimi',
  text_login_password: 'Giriş Şifresi',
  text_anti_phishing_code: 'Anti-Phishing Kodu',
  text_phishing_block_code: 'Anti-Phishing Kodu',
  text_phishing_desc: 'Bu kod sayesinde gerçek e-postaları; pishing-oltalama e-postalarından ayırt edebilir ve bu tür girişimleri engelleyebilirsiniz.',
  text_last_login: 'Son Giriş',
  text_account_mobility: 'Hesap Hareketleri',
  text_suspicious_activity: 'Size ait değil mi ?',
  text_verified: 'Doğrulandı',
  text_verification: 'Doğrulama',
  text_inprogress: 'İnceleniyor',
  // security verify common
  text_phone_verification: 'Telefon Doğrulama Kodu',
  text_email_verification: 'E-posta Doğrulama',
  text_google_verification: 'Google 2FA Doğrulama Kodu',
  text_google_code_enter: 'Doğrulama Kodunu Girin',
  text_send_code: 'Kodu gönder',
  text_sent_code: 'Adresine gönderilen Doğrulama Kodunu girin',
  text_security_verify_not_available: 'Güvenlik Doğrulaması Mevcut Değil Mi?',
  //common
  text_filter: 'Filtrele',
  text_reset: 'Sıfırla',
  text_open: 'Açık',
  text_confirm: 'Doğrula',
  text_approve: 'Onayla',
  // deposit
  deposit_title: 'Yatırma',
  available_amount: 'Kullanılabilir Bakiye',
  used_amount: 'İşlemdeki Bakiye',
  total_amount: 'Toplam Bakiye',
  tips: 'Uyarılar',
  tips_item_one: 'Lütfen gönderdiğiniz adresi kontrol ediniz.\n' + ' Yanlış adrese gönderilen tutarlar kaybolabilir.',
  tips_item_two: 'Yatırma Bildirimi için e-postanızı kontrol ediniz.',
  erc20: 'Yatırma Desteklenmiyor.',
  deposit_history: 'Yatırma Geçmişi',
  deposit_network: 'Ağ Türü',
  withdraw_history: 'Çekim Geçmişi',
  withdraw_title: 'Çekme',
  withdraw_network: 'Ağ Türü',
  //Corporate Account
  corporate_header: 'Kurumsal Hesap Doğrulama Başvurusu',
  // P2P
  p2p_cancel_btn: 'iPtal',
  p2p_information: 'Bilgiler',
  processes: 'İşlemler',
  p2p_processes: 'P2P İşlemleri',
  market: 'Market',
  p2p_market: 'P2P Market',
  place_order: 'İlan Yayınla',
  p2p_history: 'P2P İşlem Geçmişi',
  payment_settings: 'Ödeme Ayarları',
  p2p_orders: 'Emirler',
  p2p_place_new_order: 'Yeni İlan Oluştur',
  p2p_wallet_text: 'P2P Wallet',
  p2p_wallet_text_approximate_balance: 'Yaklaşık Toplam Bakiye',
  p2p_security_balance_title: 'Güvence Bedeli Nedir?',
  p2p_security_balance_info: 'Güvence bedeli, alıcı ve satıcı arasındaki güven kriterlerinden birisidir.',
  p2p_security_deposit_link: 'Güvence Bedeli Yatır',
  p2p_security_transfer_btn: 'Transfer Et',
  p2p_hide_balance: 'Bakiye Gizle',
  p2p_history_tab_heading: 'Tüm P2P İşlem Geçmişi',
  p2p_inner_table_1: 'Buyer / Seller',
  p2p_inner_table_2: 'Quantity',
  p2p_inner_table_3: 'Price',
  p2p_inner_table_4: 'Available',
  p2p_inner_table_5: 'Status',
  p2p_inner_table_6: 'Number of Talems',
  p2p_inner_table_7: 'Listing Number',
  // Froze
  froze_security: 'Güvenlik',
  froze_transactions: 'Hesap Hareketleri',
  froze_disable_account: 'Hesabınızı Devre Dışı Bırakın',
  froze_warning: 'Hesabınızı devre dışı bırakmanız halinde:',
  froze_item_one: 'Hesabınızın tüm alım-satım yetkileri devre dışı bırakılacak',
  froze_item_two: 'Hesabınızın tüm API verisi silinecek',
  froze_item_three: 'Hesabınıza bağlı tüm cihazlar silinecek',
  froze_item_four: 'Tüm çekim talepleri iptal edilecek',
  froze_item_five: 'Tüm açık emirler iptal edilecektir.',
  froze_second_warning: 'Hesabınız devre dışı bırakıldığında, tekrar etkinleştirmek için en az iki saat beklemelisiniz.',
  froze_approve: 'Hesap Dondurma İşlemini Onaylayın',
  froze_modal_title: 'Güvenlik Doğrulaması',
  froze_modal_text: 'P2P işlemlerine başlayabilmek için kimlik doğrulama işlemini tamamlamanız gerekmektedir.',
  froze_modal_sms: 'Telefon Doğrulama',
  froze_modal_google: 'Google 2FA Doğrulama',
  froze_remember_me: 'Daha Sonra Hatırlat',
  // order->P2P->open
  p2p_order_breadcrum_1: 'İşlemler',
  p2p_order_breadcrum_2: 'P2P Açık Emirler',
  p2p_order_text_tab_1: 'Tüm Emirler',
  p2p_order_text_tab_2: 'İşleniyor',
  p2p_order_heading_text_tab_2: 'Coinler',
  p2p_order_heading_text_tab_2: 'Emir Türü',
  p2p_order_heading_text_tab_2: 'Durum',
  p2p_order_field_text_1: 'Tüm coinler',
  p2p_order_field_text_2: 'Al/Sat',
  p2p_order_field_text_3: 'Tüm Durumlar',
  p2p_order_field_label_1: 'Coinler',
  p2p_order_field_label_2: 'Emir Türü',
  p2p_order_field_label_3: 'Durum',
  p2p_order_field_table_heading_1: 'Coin/Tür',
  p2p_order_field_table_heading_2: 'Miktar',
  p2p_order_field_table_heading_3: 'Fiyat ve Adet',
  p2p_order_field_table_heading_4: 'Karşı Taraf',
  p2p_order_field_table_heading_5: 'Durum',
  p2p_order_field_table_heading_6: 'Hareket',
  p2p_table_rowName_1: 'Available',
  p2p_table_rowName_2: 'Sınırı',
  // swap
  swap_change: 'Dönüştür',
  swap_how_much: 'Fiyat',
  swap_how_much_take: 'Alacağınız',
  swap_quick: 'Hızlı Takas İşlemi',
  swap_sending_text: 'Göndereceğiniz',
  swap_sending_text2: 'Alacağınız',
  swap_sending_info: 'Alacağınız yaklaşık miktarı gösterir. Gerçek miktar işlem gerçekleştikten sonra belirlenir.',
  swap_available_balance: 'Kullanılabilir Miktar:',
  swap_start_process: 'İşlemi Başlat',
  swap_rules_heading: 'Nedir?',
  swap_form_button_text: 'Şimdi Değişim Yapın',
  swap_rules: 'Hızlı Takas Nedir ?',
  swap_rule: 'Emir tahtasında çifti olan / olmayan yüzden fazla kripto para çiftini kolay bir şekilde takas edebilmenizi sağlayan bir servistir. En iyi fiyatlarla avantajlı takas yapmanı sağlar.',
  swap_text_header: 'Hızlı Takas',
  // payment
  text_bank_account_name: 'Hesap Adı',
  // otc
  otc_text_want_to_buy: 'Almak İstiyorum',
  otc_text_want_to_sell: 'Satmak İstiyorum',
  otc_text_want_to_spend: 'Harcamak İstiyorum',
  otc_text_offer: 'Teklif Al',
  otc_get_price: 'OTC Teklifi Al',
  otc_current_price: 'Size Özel Teklif',
  otc_empty_message: 'Teklif almak için lütfen miktar giriniz.',
  otc_info_message: 'İşleminize devam etmek için; aşağıdaki iletişim kanalları üzerinden Cointral yetkilisiyle iletişime geçin. Dikkat! Cointral yetkilisine sadece aşağıdaki bağlantıları kullanarak ulaşabilirsiniz.',
  otc_copied: 'Kopyalandı',
  otc_order_number: 'Emir Numarası',
  otc_security_code: 'Güvenlik Kodu',
  otc_price_per_coin: 'Birim Fiyat',
  otc_total: 'Toplam',
  otc_start_transaction: 'İşlemi Başlat',
  otc_order_history: 'Emir Geçmişi',
  otc_text_header: 'Cointral OTC Platformuna Hoşgeldiniz',
  otc_text_orderid: 'Teklif Numarası',
  // buy
  buy_spending_amount: 'Harcanan Miktar',
  buy_text_header: 'Satın Al',
  buy_you_will_get: 'Alacaksınız',
  buy_select_provider: '1. Servis Sağlayıcısını Seçiniz',
  buy_payment_detail: '2. Ödeme Detayları',
  buy_provider: 'Sağlayıcı',
  buy_total: 'Toplam',
  buy_disclaimer_header: 'Sorumluluk Reddi Beyanı',
  buy_disclaimer: 'Kredi kartı ödemelerine dair hizmetler seçmiş olduğunuz üçüncü tarafından sunulmaktadır. Lütfen hizmeti kullanmadan önce ilgili sağlayıcının Kullanım Koşullarını okuyun. Kredi kartı ödemelerine yönelik sorularınız için bizimle veya servis sağlayıcıyla iletişime geçin. Cointral, kredi kartı ödemeleri hizmetinin kullanımından doğacak herhangi bir kayıp ya da zarara yönelik hiçbir sorumluluk kabul etmez..',
  buy_terms_of_use: 'Kullanım koşullarını okudum ve kabul ediyorum.',
  buy_confirm_transaction: 'İşlemi Onayla',
  buy_continue: 'Satın Al',
  buy_text_agreement: 'Okudum ve anladım',
  buy_payment_method: 'Ödeme Methodu',
  // exchange
  exchange_open_orders: 'Açık İşlemler',
  exchange_last24H_orders: 'Son 24 Saatteki İşlemler',
  exchange_price: 'Fiyat',
  exchange_amount: 'Miktar',
  exchange_date: 'Tarih',
  exchange_pair: 'Çift',
  exchange_change: 'Değişim',
  exchange_search: 'Arama',
  exchange_type: 'Tip',
  exchange_side: 'Taraf',
  exchange_total: 'Toplam',
  exchange_status: 'Durum',
  exchange_filled: 'İşlenen',
  exchange_last_price: 'Son Fiyat',
  exchange_24h_change: 'Değişim',
  exchange_24h_high: 'En Yüksek',
  exchange_24h_low: 'En Düşük',
  exchange_24h_volume: 'Hacim',
  exchange_market: 'Piyasa',
  exchange_trade_history: 'Son İşlemler',
  exchange_text_not_working: 'Geçici olarak kullanılamamaktadır.',
  exchange_text_login: 'Giriş yapın',
  exchange_text_or: 'veya',
  exchange_text_signup: 'Yeni Üyelik',
  exchange_text_create: 'oluşturun',
  exchange_button_cancel: 'İptal',
  exchange_button_cancel_All: 'Cancel All',
  exchange_text_norecords: 'Kayıt bulunamadı.',
  exchange_text_create: 'oluşturun',
  exchange_text_invalid_price: 'Lütfen geçerli bir fiyat girin',
  exchange_text_status_volume_info: 'Kripto-Kripto likitidesi uluslararası piyasalardan sağlanmaktadır.',
  // verify
  verify_header: 'Güvenlik Doğrulaması',
  verify_text_security_verification: 'Güvenliğiniz için lütfen aşağıdaki doğrulamayı tamamlayın.',
  verify_text_info: 'İki faktörlü doğrulamayı devre dışı bırakmak, risklidir. Devre dışı bırakırsanız, mümkün olan en kısa sürede yeniden etkinleştirmeniz önemle tavsiye edilir. 2FA devre dışı bırakıldıktan sonra 24 saat boyunca çekim işlemi gerçekleştiremezsiniz.',
  verify_email_title: 'E-posta Doğrulama Kodu',
  verify_2fa_title: 'Google Doğrulama kodu',
  verify_phone_title: 'Telefon Doğrulama Kodu',
  verify_2fa_info: 'Google Authenticator kodunu girin',
  verify_send_button: 'Gönder',
  verify_enter_code: 'Kodu Giriniz',
  verify_send_code: 'Kod İste',
  verify_new_password: 'Yeni Parola',
  verify_confirm_password: 'Parola Onayı',
  // main-wallet
  main_wallet_select: 'Seç',
  main_wallet_label: 'Ana Cüzdan',
  main_text_withdraw: 'Çekme',
  main_text_deposit: 'Yatırma',
  main_wallet_amount: 'Miktar',
  main_wallet_address: 'Adres',
  main_wallet_date: 'Tarih',
  main_wallet_asset: 'Birim',
  main_wallet_status: 'Durum',
  main_wallet_available_balance: 'Kullanılabilir Bakiye',
  main_wallet_withdraw_fee: 'İşlem Ücreti',
  main_wallet_will_get: 'Alacaksınız',
  main_wallet_send: 'Gönder',
  main_wallet_tag_address: 'Adres Tagı',
  main_wallet_networktab1: ' TAB1',
  main_wallet_networktab2: 'TAB2',
  main_wallet_memo_info: 'Başarıyla yatırmak için hem MEMO hem de adres gereklidir.',
  main_wallet_memo_warning: 'Lütfen MEMO bilginizi kontrol ediniz. MEMO bilginizi yanlış girmeniz durumunda gönderilen tutarlar kaybolabilir.',
  main_wallet_withdraw_info: 'Lütfen gönderdiğiniz adresi kontrol ediniz. Yanlış adrese gönderilen tutarlar kaybolabilir.',
  main_wallet_email: 'E-posta',
  main_wallet_coin_address: 'Adres',
  main_wallet_exchange_link: 'Al/Sat ',
  main_wallet_approximate_balance: 'Yaklaşık Toplam Bakiye',
  main_wallet_show_balance: 'Bakiye Göster',
  main_wallet_history: 'Cüzdan Geçmişi',
  main_wallet_transfer: 'Transfer',
  main_wallet_search: 'Ara',
  main_wallet_reset: 'Sıfırla',
  main_wallet_transfer: 'Transfer',
  main_wallet_deposit: 'Yatır',
  main_wallet_withdraw: 'Çek',
  main_wallet_trade: 'Al-Sat',
  main_wallet_address: 'Adres',
  // fiat-wallet
  fiat_wallet_select: 'Seç',
  fiat_wallet_label: 'TL Cüzdan',
  fiat_wallet_withdraw: 'TL Çekme',
  fiat_wallet_deposit_label: 'TL Yatırma',
  fiat_wallet_min_amount: 'Minimum Çekim',
  fiat_wallet_withdraw_fee: 'İşlem Ücreti',
  fiat_wallet_daily_withdraw_limit: 'Günlük Çekim Limiti',
  fiat_wallet_label_bank_account: 'Lütfen banka hesabı seçiniz',
  fiat_wallet_new_bank: 'Banka Hesabı Ekle',
  fiat_wallet_amount: 'Gönderilecek Tutar',
  fiat_wallet_quantity: 'Tutar',
  fiat_wallet_status: 'Durum',
  fiat_wallet_address: 'Adres',
  fiat_wallet_date: 'Tarih',
  fiat_wallet_asset: 'Birim',
  fiat_wallet_deposit: 'Yatırma',
  fiat_wallet_send: 'Gönder',
  fiat_wallet_select: 'Seç',
  fiat_wallet_deposit_history: 'TL Yatırma Geçmişi',
  fiat_wallet_text_bank: 'Banka Adı',
  fiat_wallet_text_receiver: 'Alıcı Adı',
  fiat_wallet_text_deposit_code: 'Yatırma Kodunuz',
  fiat_wallet_text_condition1: ' Farklı bir kişinin hesabından yapılan transferler kabul edilemez.',
  fiat_wallet_text_condition2: 'Kredi kartı ile yapılan transferler kabul edilemez.',
  fiat_wallet_text_condition3: 'Şube veznelerinden yapılan transferler kabul edilemez.',
  fiat_wallet_text_condition4: 'Bankamatik kullanılarak yapılan transferler kabul edilemez.',
  fiat_wallet_text_condition5: 'Yalnızca TL olarak yapılan transferler kabul edilmektedir.',
  fiat_wallet_text_condition6: 'Açıklama bölümünde yatırma kodu bulunmayan transferler kabul edilmeyecektir.',
  fiat_wallet_text_deposit_form: 'ÖNEMLİ HATIRLATMALAR',
  fiat_wallet_text_confirm_button: 'Onaylıyorum',
  fiat_wallet_text_kyc_warning: 'Kimlik bilgilerinizi doğrulamadan, banka hesap bilgilerine erişimezsiniz. TL işlemlerine başlamak için kimlik doğrulamasını tamamlayın.',
  fiat_wallet_text_kyc_warning_btn: 'Kimlik Doğrulama Başlat',
  //History
  history_title: 'İşlem Geçmişi',
  history_type: 'Tip',
  history_text_withdraw: 'Çekme',
  history_text_deposit: 'Yatırma',
  history_text_info: 'Bilgi',
  history_text_from: 'Nereden',
  history_text_to: 'Nereye',
  history_text_search: 'Ara',
  history_text_reset: 'Sıfırla',
  history_tab_withdraw: 'Yatırma Çekme',
  history_tab_transfer: 'Transfer',
  history_tab_mainwallet: 'Ana Cüzdan',
  history_tab_trywallet: 'TL Cüzdanı',
  history_amount: 'Miktar',
  history_address: 'Adres',
  history_date: 'Tarih',
  history_asset: 'Birim',
  history_status: 'Durum',
  history_transfer_list_all: 'Hepsi',
  //Login
  login_text_invalid_phone: 'Geçersiz Telefon Numarası',
  login_text_forgot_password: 'Şifrenizi mi unuttunuz?',
  login_text_register: 'Kayıt Ol',
  login_text_info: "Lütfen doğru URL'yi ziyaret ettiğinizden emin olun!",
  login_text_email_info: 'Lütfen E-posta adresinizi girin',
  login_text_phone_info: 'Lütfen telefon numaranızı girin',
  login_text_reset_password: 'Şifre Sıfırla',
  login_text_scan: 'Tara',
  login_text_qr: 'Qr Kod',
  login_text_already_register: 'Zaten üye misiniz?',
  login_text: 'Giriş Yap',
  login_title_create_account: 'Ücretsiz Hesap Oluştur',
  login_text_create_account: 'Hesap Oluştur',
  login_subtitle_create_account: 'Cointral | Hoşgeldiniz',
  login_text_term_of_use: 'Aydınlatma metnini okudum, kabul ediyorum.',
  login_text_term_of_use_mobile: 'Mobil Aydınlatma Metnini okudum, kabul ediyorum.',
  login_text_cointral_terms: 'Cointral Kullanıcı Sözleşmesi',
  login_v: 'a123',
  //Security Components
  security_components_passport: 'Pasaport',
  security_components_identity_card: 'Kimlik Kartı',
  security_components_driver_license: 'Ehliyet',
  security_components_male: 'Erkek',
  security_components_female: 'Kadın',
  //Activity
  activity_date: 'Tarih',
  activity_browser: 'Tarayıcı',
  activity_description: 'Açıklama',
  activity_ip_address: 'IP Adres',
  //corporate
  corporate_competents_name: 'Ad',
  corporate_competents_surname: 'Soyad',
  corporate_company_title: 'Şirket Adı',
  corporate_email: 'E-posta',
  corporate_phone: 'Telefon',
  corporate_area_code: 'Alan Kodu',
  corporate_send_btn: 'Gönder',
  corporate_appeal_title: 'Tebrikler İşlem Tamamlandı!',
  corporate_appeal_text: 'Kimlik doğrulama talebiniz bize ulaştı. Sizi en kısa sürede bilgilendireceğiz.',
  corporate_homepage_btn: 'Anasayfaya Dön',
  // payment
  payment_text_kyc: 'Kimlik Doğrulamanızı Tamamlayınız.',
  payment_text_cancel_btn: 'İptal Et',
  text_welcome: 'Hoşgeldiniz',
  //orders
  orders_text_paymentid: 'ID',
  orders_text_date: 'Tarih',
  orders_text_provider: 'Sağlayıcı',
  orders_text_fiat_amount: 'Tutar',
  orders_text_coin_amount: 'Miktar',
  orders_text_status: 'Durum',
  orders_text_buy_sell_total: 'Alım-Satım Toplamı',
  orders_text_symbol: 'Çift',
  orders_text_side: 'Taraf',
  orders_text_price: 'Fiyat',
  orders_text_quantity: 'Miktar',
  orders_text_type: 'Tip',
  orders_text_executed_quantity: 'Gerçekleşen',
  orders_text_total: 'Toplam',
  orders_text_executed_total: 'Gerçekleşen Toplam',
  orders_text_stop_price: 'Stop-Limit',
  //swap history
  swap_history_date: 'Tarih',
  swap_history_amount: 'Miktar',
  swap_history_price: 'Fiyat',
  swap_history_status: 'Durum',
  swap_history_amount: 'Miktar',
  swap_history_transaction_id: 'İşlem ID',
  //reference
  reference_text_reference_code: 'Referans Kodunuz',
  reference_text_invite: 'Şimdi Davet Et',
  reference_text_description: 'Arkadaşlarınızı mesaj veya e-posta yoluyla davet etmek için size özel bağlantınızı kullanın.',
  reference_text_customized_link: 'Size Özel Bağlantı',
  reference_text_customize_link: 'Bağlantıyı Özelleştir',
  reference_text_reference_rate: 'Referans Oranınız',
  reference_text_reference_rate2: 'Arkadaslarinizin alacagi',
  reference_text_reference_account: 'Referans Hesabınız',
  reference_text_reference_income: 'Geliriniz',
  reference_text_reference_count: 'Referans Sayısı',
  reference_text_reference_create: 'Oluştur',
  reference_text_reference_history: 'Referans Geçmişi',
  //navbar
  navbar_main_wallet: 'Ana Cüzdan',
  navbar_fiat_wallet: 'TL Cüzdan',
  navbar_p2p_wallet: 'P2P Cüzdan',
  navbar_wallet_history: 'Cüzdan Geçmişi',
  navbar_p2p_wallet: 'P2P Cüzdan',
  navbar_tab_balance: 'Bakiye',
  navbar_tab_deposit: 'Yatırma',
  navbar_tab_withdraw: 'Çekme',
  //price
  price_approximate_balance: 'Yaklaşık Toplam Bakiye',
  price_try_wallet: 'TL Cüzdanı',
  price_hide_balance: 'Bakiye Gizle',
  price_wallet_history: 'Cüzdan Geçmişi',
  price_withdraw: 'Çekme',
  price_deposit: 'Yatırma',
  price_withdraw_btn: 'Çek',
  price_deposit_btn: 'Yatır',
  price_search: 'Ara',
  price_reset: 'Sıfırla',
  price_trade: 'Al-Sat',
  //Transfer
  transfer_sender: 'Gönderici',
  transfer_receiver: 'Alıcı',
  transfer_available_amount: 'Kullanılabilir Miktar',
  transfer_start: 'İşlemi Başlat',
  antiphishing_text_code: 'Anti-Phishing Kodu',
  antiphishing_text_warning: 'Hiçbir zaman şifrenizi, 2FA ve Anti-Pishing kodunuzu Cointral destek ekibi dahil kimseyle paylaşmayınız.',
  antiphishing_text_title: 'Anti-Pishing Kodu Nedir?',
  antiphishing_text_description: "Anti-Pishing Kodu, 'sahte' Cointral web sitelerinden ya da e-posta adreslerinden gelen oltalama girişimlerini engellemeye yardımcı olan bir koddur. Bu kod sayesinde gerçek e-postaları ve Phishing (Oltalama) e-postalarından ayırt edebilir ve bu tür girişimleri engelleyebilirsiniz.",
  antiphishing_text_how_it_work_title: 'Nasıl Çalışır?',
  antiphishing_text_how_it_work_description: 'Anti-Pishing Kodunuzu belirlediğinizde, bu kod size tarafımızdan gönderilen tüm e-postalara dahil edilir.',
  antiphishing_text_confirm: 'Onayla',
  antiphishing_text: 'Anti-Phishing',
  //password
  password_description: 'Güvenliğiniz için parola değişiminden sonra 24 saat çekim işlemi yapamayacaksınız.',
  //Navbar
  navbar_main_wallet: 'Ana Cüzdan',
  warning_title: 'Uyarı',
  reset_password: 'Giriş Parolasını Sıfırla',
  send_email_text: '{email} adresine gönderilen 6 haneli kodu girin',
  send_sms_text: '{phn} numarasına gönderilen 6 haneli kodu girin',
  invalid_phone_no: 'Geçersiz Telefon No',
  text_spot_open_orders: 'Spot Açık Emirler',
  text_spot_order_history: 'Spot Emir Geçmişi',
  text_spot_buying_selling: 'Alım/Satım Geçmişi',
  text_buy_crypto: 'Kripto Al',
  text_third_party_payments: 'Üçüncü Taraf Ödemeleri',
  text_otc_buying_selling: 'OTC Alım/Satımları',
  text_otc_market: 'Piyasalar',
  text_swap: 'Hızlı Takas',
  text_exchange: 'Borsa',
  text_otc: 'OTC',
  header_text_buy_sell: 'Al-Sat',
  header_text_security: 'Güvenlik',
  header_text_identification: 'Identification',
  header_text_reference: 'Referans',
  header_text_logout: 'Çıkış Yap',
  history_text_wallet_history: 'Cüzdan Geçmişi',
  history_text_deposit_withdraw: 'Yatırma/Çekme',
  history_text_fiat_wallet: 'TL Cüzdanı',
  history_text_type: 'Tip',
  history_text_not: 'Not',
  history_text_from: 'Nereden',
  history_text_to: 'Nereye',
  history_text_status: 'Durum',
  history_text_all: 'Hepsi',
  history_text_amount: 'Miktar',
  history_text_search: 'Arama',
  history_text_reset: 'Sıfırla',
  text_all: 'Tümü',
  //device management
  device_management_text_info: 'Bu cihazların hesabınıza erişimine izin veriliyor',
  device_management_text_more: 'Daha Fazla',
  device_management_text_date: 'Tarih',
  device_management_text_ipadress: 'Ip Adres',
  device_management_text_more: 'Daha Fazla',
  device_management_text_delete: 'Sil',
  //ActionTab
  text_buy_asset: '{asset} Al',
  text_sell_asset: '{asset} Sat',
  //placeholders
  placeholders_text_select_document_type: 'Doküman Tipi Seçiniz',
  placeholders_text_search: 'Arama',
  placeholders_text_docnumber: 'TCKN/YKN',
  placeholders_text_stop: 'Stop',
  placeholders_text_limit: 'Limit',
  placeholders_text_price: 'Fiyat',
  placeholders_text_amount: 'Miktar',
  placeholders_text_total: 'Toplam',
  placeholders_text_select: 'Seçiniz',
  placeholders_text_optional: 'Opsiyonel',
  //SymbolListMobile
  symbol_list_mobile_text_change: 'Değiştir',
  symbol_list_mobile_text_pair: 'Çift',
  symbol_list_mobile_text_last_price: 'Son Fiyat',
  symbol_list_mobile_text_changing: 'Değişim',
  //Account
  account_text_dashboard: 'Hesabım',
  account_text_bank: 'Banka',
  account_text_security: 'Güvenlik',
  account_text_notification: 'Bildirim',
  account_text_reference: 'Referans',
  account_text_activity: 'Hareketler',
  account_text_preferences: 'Tercihler',
  account_text_management: 'Yönetim',
  account_text_antiphishing: 'Anti-phishing',
  account_text_change_password: 'Şifre Değiştir',
  //Security Setting
  security_setting_text_title: 'Hesabınızın Güvenliğini Artırın',
  security_setting_text_2fa_enable: '2FA Etkinleştirin',
  security_setting_text_id_authenticate: 'Kimlik Doğrulaması Yapın',
  security_setting_text_antiphishing: 'Anti-Phishing Kodu Aktfileştirin',
  //network
  network_text_deposit_not_supported: 'Yatırma desteklenmiyor',
  network_text_withdraw_not_supported: 'Çekme desteklenmiyor',
  network_text_withdraw_address: 'Alıcının {asset} Adresi',
  //tips
  deposit_tips: 'Uyarılar',
  deposit_tips_item_one: 'Lütfen gönderdiğiniz adresi kontrol ediniz.\n' + ' Yanlış adrese gönderilen tutarlar kaybolabilir.',
  deposit_tips_item_two: 'Yatırma Bildirimi için e-postanızı kontrol ediniz.',
  withdraw_tips: 'Uyarılar',
  withdraw_tips_item_one: 'Lütfen gönderdiğiniz adresi kontrol ediniz.\n' + ' Yanlış adrese gönderilen tutarlar kaybolabilir.',
  withdraw_tips_item_two: 'Çekme Bildirimi için e-postanızı kontrol ediniz.',
  fiat_wallet_withdraw_history: 'TL Çekme Geçmişi',
  fiat_wallet_label_bank_account: 'Lütfen bir banka hesabı ekleyiniz',
  fiat_wallet_history: 'Cüzdan Geçmişi',
  //bank-account
  bank_accounts_tips: 'Uyarılar',
  bank_accounts_tips_item_1: 'Yalnızca kendi adınıza olan hesabınızı ekleyiniz.',
  bank_accounts_tips_item_2: 'Kredi kartı ile yapılan transferler kabul edilemez.',
  bank_accounts_tips_item_3: 'Şube veznelerinden yapılan transferler kabul edilemez.',
  bank_accounts_tips_item_4: 'Bankamatik kullanılarak yapılan transferler kabul edilemez.',
  bank_accounts_tips_item_5: 'Yalnızca TL olarak yapılan transferler kabul edilmektedir.',
  bank_accounts_tips_item_6: 'Açıklama bölümünde yatırma kodu bulunmayan transferler kabul edilmeyecektir.',
  //fiat-wallet
  fiat_wallet_tips: 'Uyarılar',
  fiat_wallet_tips_item_one: 'Yalnızca kendi adınıza olan hesabınızı ekleyiniz.',
  fiat_wallet_tips_item_two: 'Hesap bilgilerinizin yanlış girilmesi transfer sürenizin uzamasına sebep olabilir.',
  //new_password screen
  password_text_create_pass: 'Yeni Şifre Oluştur',
  password_text_info: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  corporate_text_success: 'Tebrikler İşlem Tamamlandı!',
  corporate_text_info: 'Kimlik doğrulama talebiniz bize ulaştı. Sizi en kısa sürede bilgilendireceğiz.',
  corporate_text_return_home_page: 'Anasayfaya Dön',
  corporate_text_title: 'Kurumsal Bilgiler',
  text_required_field: 'Zorunlu Alan!',
  text_security_deposit: 'Güvence Bedeli',
  main_wallet_text_available: 'Kullanılabilir',
  main_wallet_text_used: 'İşlemde',
  main_wallet_text_btc_amount: 'BTC Karşılığı',
  main_wallet_text_total: 'Toplam',
  placeholders_text_from_date: 'Başlangıç Tarihi',
  placeholders_text_to_date: 'Bitiş Tarihi',
  placeholders_text_type: 'İşlem Tipi',
  //TİP
  BUY: 'ALIŞ',
  SELL: 'SATIŞ',
  //Banner Text
  banner_heading_text: 'KATILMAK İÇİN FORMU DOLDUR!',
  banner_desc_text: 'Arkadaşlarınızı davet etmek için size özel referans kodunu veya referans bağlantısını kullanın. Referanslarınız Cointral’de işlem yaptığınızda %25 referans geliri kazanın.',
  banner_desc_text2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
  //History
  history_symbol: 'Çift',
  history_actual_qty: 'İşlenen',
  history_average_price: 'Ortalama Fiyat',
  history_stop_limit: 'Stop-Limit',
  history_quote_qty: 'Toplam',
  history_price: 'Fiyat',
  history_side: 'Taraf',
  history_commission: 'Komisyon',
  history_commission_asset: 'Komisyon Birim',
  history_total: 'Toplam',
  //OTC
  otc_orderid: 'Sipariş Numarası',
  otc_type: 'Tip',
  otc_status: 'Durum',
  otc_in_amount: 'Gönderilen',
  otc_out_amount: 'Alınan',
  otc_date: 'Tarih',
  //Cash
  cash_heading_text: 'Nakit',
  cash_sub_heading_text: 'Bakiye',
  cash_form_deposit_heading_text: 'Yatırma',
  cash_form_deposit_sub_heading_text: '',
  cash_form_dpn_heading_text: 'Çekme',
  cash_form_dpn_sub_heading_text: '',
  cash_tips: 'İşlemlerinizi yalnızca USDT (Tether) olarak gerçekleştirebilirsiniz.',
  cash_form_btn_text: 'Talep Oluştur',
  cash_deposit_table_text: 'Yatırma Geçmişi',
  cash_withdraw_table_text: 'Çekme Geçmişi',
  text_cash_cancel_feedback: '',
  //New Account 2
  heading_text_1: 'Türkiye’nin En Düşük Komisyon Oranı ile Kolayca Bitcoin Al',
  heading_text_2: 'Bitcoin, Ethereum, XRP ve 200+ altcoin çeşidi ile geleceğe yatırım yap!',
  heading_text_3: '%0,1 masrafla avantajlı kripto para alım-satım ve takas işlemlerine başlamak için;',
  banner_item_1: 'Üye Ol',
  banner_item_2: 'Para Yatır',
  banner_item_3: 'Kripto Para Yatırımına Başla!',
  banner_sub_item_heading_1: 'En İyi Fiyatlar',
  banner_sub_item_heading_2: 'Güvenli ve Hızlı İşlemler',
  banner_sub_item_heading_3: '7 / 24 Destek',
  banner_sub_item_desc_1: 'Dünyanın en popüler kripto para borsaları ile entegre olan Cointral kullanıcılarına en iyi fiyat ayrıcalığını tanımaktadır.',
  banner_sub_item_desc_2: 'Google 2FA, SMS Doğrulama ve Anti-Phishing gibi güvenlik önlemleri ile kullanıcılarına yüksek düzeyde güvenlik sunar. Şubelerimizi ziyaret ederek de bilgi ve destek alabilirsiniz.',
  banner_sub_item_desc_3: 'Herhangi bir soru ve öneriniz için destek ekibimizden yardım alabilirsiniz',
  banner_video_text: 'Bir kripto para platformunda en fazla ne olabilir mi diyorsun?',
  //cash status
  cancelled: 'İptal Edildi',
  ready_for_cash: 'Nakit için hazır',
  ready_for_pay: 'Ödeme için hazır',
  done: 'Tamamlandı',
  dsc_enable_email: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  tll_enable_email: 'Güvenlik Doğrulaması',
  ttl_disable_2fa: 'Google Authenticator Devre Dışı Bırak',
  dsc_disable_2fa: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_disable_sms: 'SMS Doğrulama Devre Dışı Bırak',
  dsc_disable_sms: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_enable_sms: 'SMS Doğrulama Aktifleştir',
  dsc_enable_sms: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_enable_2fa: 'Google Authenticator Aktifleştir',
  dsc_enable_2fa: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_froze_token: 'Hesabı Dondur',
  dsc_froze_token: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_verify_customer: 'Güvenlik Doğrulaması',
  dsc_verify_customer: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_enable_froze_token: 'Hesabı Aktfileştir',
  dsc_enable_froze_token: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_unverified_device: 'Farklı Cihazı Onaylayın',
  dsc_unverified_device: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  ttl_twofa_token: 'Güvenlik Doğrulaması',
  dsc_twofa_token: 'Hesabınızın güvenliği için aşağıdaki adımları takip ediniz.',
  //cash
  cash_title: 'Nakit İşlem',
  cash_deposit_amount: 'Yatırmak İstediğiniz Miktar',
  cash_withdrawal_amount: 'Çekmek İstediğiniz Miktar',
  cash_desc1_deposit: 'Yalnızca kendi adınıza kayıtlı hesaba yatırma işlemi gerçekleştirebilirsiniz.',
  cash_desc1_withdraw: 'Yalnızca kendi adınıza kayıtlı hesaba çekme işlemi gerçekleştirebilirsiniz.',
  cash_desc2: 'İşlem sırasında Kimlik Belgenizi ibraz etmeniz zorunludur.',
  cash_desc3: 'Talep oluşturduğunuz tutar işlem yaptığınız tutara eşit olmalıdır.',
  cash_desc4_deposit: 'Yalnızca USDT (Tether) yatırma talebi oluşturabilirsiniz.',
  cash_desc4_withdraw: 'Yalnızca USDT (Tether) çekme talebi oluşturabilirsiniz.',
  cash_desc5: 'İşlem sırasında iki aşamalı doğrulama gerekmektedir.',
  cash_desc6: 'İşlem yalnızca Cointral Şubelerinde gerçekleşmektedir.',
  //NewAccount 3
  new_account_page_title: 'Cointral’de Para Çekmek Çok Basit!',
  new_account_page_subtitle1: 'Çekim miktarını belirle',
  new_account_page_subtitle2: 'Banka Bilgisi ve IBAN adresiniz yaz',
  new_account_page_subtitle3: 'Paranız hesabınızda!',
  new_account_page_center_heading_1: 'TL İşlemleri',
  new_account_page_center_heading_2: 'Cointral.com’da kripto para işlemlerini TL ile gerçekleştirebilirsin!',
  new_account_page_center_heading_3: 'Vakıfbank, Denizbank ve Ziraat Bankası güvencesi ile kolayca TL yatır!',
  //Login
  login_tab_email: 'E-posta',
  login_tab_mobile: 'Telefon',
  dashboard_text_last_login: 'Son giriş zamanı',
  dashboard_text_referal_info: '% 25 referans geliri kazanın: Şimdi arkadaşlarınızı davet edin!',
  bank_accounts_text_button: 'Banka Hesabı Ekle',
  bank_accounts_text_friendly_name: 'Hesap Adı',
  bank_accounts_text_delete: 'Sil',
  bank_accounts_text_title: 'Banka Hesap Listesi',
  bank_accounts_text_error_message: 'En fazla 3 banka hesabı eklenebilir.',
  exchange_text_try_status_volume_info: 'Yüksek hacimli TL işlemleri için OTC birimimizle iletişime geçebilirsiniz.',
  exchange_text_try_status_volume_info: 'Yüksek hacimli TL işlemleri için OTC birimimizle iletişime geçebilirsiniz.',
  reference_text_customize: 'Özelleştir',
  fiat_wallete_withdraw_order_id: 'İşlem Numarası: ',
  preferences_text_telegram_tooltip: 'Botu başlatmak için telegramdan bu kullanıcıya mesaj atmalısınız'
});

/***/ })

};;
//# sourceMappingURL=lang-tr-TR.js.map